apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
DeploymentSpec:
  template:
    spec:
      containers:
        - name: currency-converter
          env:
            - name: FLASK_ENV
              value: "development"
