apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBvCxJ7v0u4vn3kde2LoNhF0VOnIbqKJNDCl6fcH2Xjr3Wj6Gfi8ZoJMkf2PNLYhwP7mqjXDfNfnWUcmvSoLgxyZXBSJa3UDsbQbKUlY1oIs74B9cTWNgk9BLpGOQKsA2DRwQ3mPR4pK7+DhqCUtc88NkX9/xpgBC2sJu04PqSv0hYlBJvCMFEguK69EggyrPXXJ5VOZm27H54VNO2B50qqktrE2k3fkAFS1gUaV1GXjRpb92RsB34qoDT0Hhj6jKRPehEPrgxkwfv1cSJCeP7+DT1UhF2cy6sBVKit3EQNVt4xo+dm2G5oTAKx8Av1akFavNvrXxIiP2BiTyy99T8i/rdYHcXl/+Q5GNxh6JDc2FCTrf+Im0WkHSe9n2aHngR/btICwK+ftD+Wl67lPTNyCj6KelyjGHAsvmEyV6OwbYqqA+QnyKbR2smUGV5D3SKonrrkAktHyLKra5U7i+012SHPxzxFsoSPXfBLfjW67rg5IoIxBUcUwiyuNyo2S5czNy0ot1XEv3pzk0iiwwDXjJmvbXubmjleUh4BraEnE/8IFTd1j5NQE3UUFP6aSXtM9EdPDd+1ToheBFSoC95LjkdUGsRxgJzq8+Jdd5VLVqfLhRFdHxr6nbkNnDp6hUIKM+l6W31Z+J88UEMmwdOaMWurBC0bsyQjBoHaEoRud5IeXfq55LKvXipNdMi3n9ImdwZb9ts=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
